### ISSUE TITLE
Making a demo using Jupyter notebooks

### ISSUE THREAD

**Issue by alex-konovalov** [xpan-eileen/sotgrps#2]
Hi @xpan-eileen, I thought you might also be interested in making a demo of this packages runnable in the cloud in a Jupyter notebook, since it's not part of the standard GAP distribution. You can look at the template at https://github.com/rse-standrewscs/gap-binder-template, try some examples listed at the bottom of the README, and I am happy to give a demo and help to set this up!

**Comment by xpan-eileen** [comment]
Dear Alex,

Thanks for your messages and suggestions, and sorry about the late reply to your earlier email! I was trying to finalise the thesis that was meant to complement the package last week.

Thank you for the links; I’ll only have time to look into it later this week. I probably need a little bit of time to familiarise with Jupyter first as I’ve never used it before and I’m actually very new to coding (this is also the first time I wrote a GAP package).

Regards and thanks,
Eileen

________________________________
Von: Alexander Konovalov ***@***.***>
Gesendet: Dienstag, Juni 1, 2021 22:28
An: xpan-eileen/sotgrps_gap_pkg
Cc: xpan-eileen; Mention
Betreff: [xpan-eileen/sotgrps_gap_pkg] Making a demo using Jupyter notebooks (#2)


Hi @xpan-eileen<https://github.com/xpan-eileen>, I thought you might also be interested in making a demo of this packages runnable in the cloud in a Jupyter notebook, since it's not part of the standard GAP distribution. You can look at the template at https://github.com/rse-standrewscs/gap-binder-template, try some examples listed at the bottom of the README, and I am happy to give a demo and help to set this up!

**Comment by alex-konovalov** [comment]
@xpan-eileen That's fine - and good luck with finalising the thesis! You can also see appendices C and D in an earlier OpenDreamKit report https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP5/D5.15/report-final.pdf to see some more motivation and screenshots.

**Comment by xpan-eileen** [comment]
Hi @alex-konovalov, 
Thanks again for the links! I was trying to create a GAP Jupyter notebook following the instruction, but then I got stuck at the codecov.io step (step 6). In theory I have added the files and directory but when I logged in to codecov.io all I could see is just "no repos detected". I am not sure what to do from here, but I think workflow is somewhat working even though I got "Run failed" notification every time I pushed a change. I thought to continue with the next step and added the Dockerfile but then I got stuck again as I am not sure how to render the Binder badge without having a URL from codecov.io. Sorry about the hassle but I am quite stuck and was wondering if I could get some extra tips. Thanks!

**Comment by alex-konovalov** [comment]
Hi @xpan-eileen - is there a repository at which I can have a look?

**Comment by xpan-eileen** [comment]
Hi @alex-konovalov Yes, I tried to implement some preliminary functions in a repo and I just invited you to collaborate. Thanks!

**Comment by alex-konovalov** [comment]
Thanks @xpan-eileen, I see what's going on there. 

First, it tries to run tests, but fails, because files in the `tst` subdirectory are empty - they need to follow example e.g. in https://github.com/rse-standrewscs/gap-binder-template/tree/master/tst

Second, the Binder part may actually work due to the presence of the Dockerfile - however, the URL for the binder badge in the README file is incorrect, does not point to your repository.

Fixing that, you may be able to start an instance on Binder and create a new Jupyter notebook - however, you will not be able to load sotgrps files from there, since they are in https://github.com/xpan-eileen/sotgrps_gap_pkg - either you need to modify the Dockerfile to add a step of getting your package in one or another way, or, alternatively (what I had actually in mind) instead of creating a separate repository with Jupyter demo, make _this_ repository binder-ready (an example of a GAP package doing that: https://github.com/nathancarter/jupyterviz)

The https://github.com/rse-standrewscs/gap-binder-template is actually mixing together two things, perhaps not very clearly - test files, needed for continuous integration, code coverage etc., and making repository binder-ready to show Jupyter-based demos. You can do any of these, or both. Adding test files is a good practice to check that your software is correct, and is highly recommended. My point was to show how you can combine both and reduce code duplication. But as a small example which does not have tests you can see e.g. https://github.com/alex-konovalov/Kaplansky-units-counterexample.

I'd be happy to set up a call and help to make this repository binder-ready - please let me know if this would be helpful!

**Comment by xpan-eileen** [comment]
Thanks @alex-konovalov! I understand that the address I had for the Binder badge isn't correct. Because I couldn't get my own one from code cover site so I left it. I wasn't sure if the the tst subdirectory is for testing my package or testing the binder function, so I just left it empty. I do have a bunch of test functions for sotgrps but some of them are designed to run indefinitely until an error is found, so I thought not to add it in yet. Meanwhile, I finally managed to install the GAP kernel in Jupyter, but maybe because I haven't set up a proper binder it keeps complaining about connection loss. 

It would be great to make this repo binder-ready but I am still very lost... I am sorry about the hassle, but I would really appreciate a call, if that's possible. Are you in UK timezone? May I please ask when might work for you?

**Comment by alex-konovalov** [comment]
@xpan-eileen great - let's sort out the call setup by email then.

**Comment by xpan-eileen** [comment]
@alex-konovalov Thanks again for your help! I have added in a demo notebook, which should be accessible through the binder badge in README.md now. Could you please let me know if it works on your end? Thanks heaps!

**Comment by alex-konovalov** [comment]
Thanks @xpan-eileen!

Unfortunately, this setup does not work any more
```
Waiting for build to start...

Container engine initialization error: ('Check if docker is running on the host.', DockerException("Error while fetching server API version: ('Connection aborted.', BlockingIOError(11, 'Resource temporarily unavailable'))"))
```
and I have similar problem with https://github.com/rse-standrewscs/gap-binder-template

That was somehow envisaged - while good for short and may be medium term reproducibility, eventually setup starts to cramble. I would like to look at alternatives, e.g. switching to GitHub container registry and/or using Deepnote notebooks - https://community.deepnote.com/c/showcase/using-gap-in-deepnote
